CREATE SCHEMA bbs;
USE bbs;
CREATE TABLE account (
  name VARCHAR(15) NOT NULL,
  password VARCHAR(32) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY (name)
) CHARSET=UTF8;
CREATE TABLE blah (
    name VARCHAR(15) NOT NULL,
    date TIMESTAMP NOT NULL,
    txt TEXT NOT NULL,
    FOREIGN KEY (name) REFERENCES account(name) 
) CHARSET=UTF8;